FROM ubuntu:20.04

WORKDIR /usr/src/app

EXPOSE 5001

RUN apt-get update && apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash && apt install -y nodejs

COPY ./material-applications/example-frontend/package* ./

RUN npm install && npm install -g serve

COPY ./material-applications/example-frontend .

ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN useradd -m appuser

USER appuser

RUN npm run build

CMD ["serve", "-s", "-l", "5001", "build"]

# docker build -t front-end -f Dockerfile.front . && docker run -p 5001:5001 front-end