FROM ubuntu:20.04

WORKDIR /usr/src/app

EXPOSE 8080

RUN apt-get update && apt-get install -y wget

RUN wget https://go.dev/dl/go1.16.15.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.16.15.linux-amd64.tar.gz && rm -rf go1.16.15.linux-amd64.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}" PORT=8080 REQUEST_ORIGIN=http://localhost:5000 REDIS_HOST=

COPY ./material-applications/example-backend .

RUN go build

CMD ["./server", "."]

