FROM golang:1.25-alpine AS builder

WORKDIR /usr/src/app

COPY ./material-applications/example-backend/go.mod ./material-applications/example-backend/go.sum ./
RUN go mod download

COPY ./material-applications/example-backend ./

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o server

FROM alpine:3.22

WORKDIR /usr/src/app

EXPOSE 8080

ENV PORT=8080
ENV REQUEST_ORIGIN=http://localhost:5000

RUN adduser -D appuser

COPY --from=builder /usr/src/app/server ./server

USER appuser

CMD ["./server", "."]