services:
  front-end:
    image: front-end:latest
    ports:
      - 5001:5001
  
  back-end:
    image: back-end:latest
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:7-alpine