FROM ubuntu:20.04

WORKDIR /usr/src/app

EXPOSE 5001

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates && \
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y --no-install-recommends nodejs && \
    apt-get purge -y curl && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY ./material-applications/example-frontend/package* ./

RUN npm install && npm install -g serve && npm cache clean --force

COPY ./material-applications/example-frontend .

ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN npm run build && useradd -m appuser 

USER appuser

CMD ["serve", "-s", "-l", "5001", "build"]

# docker build -t front-end -f Dockerfile.front . && docker run -p 5001:5001 front-end